version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: malewa_fac_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: malewa_fac
    ports:
      - "3306:3306"
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
